version: '3'
services:
    mysql:
        image: mysql
        cap_add:
            - SYS_NICE
        container_name: planning_mysql
        command: mysqld --default-authentication-plugin=mysql_native_password
        volumes:
            - ./mysql:/var/lib/mysql/
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: plandb
            MYSQL_USER: admin
            MYSQL_PASSWORD: admin

    strapi:
        image: strapi/strapi
        container_name: planning_strapi
        environment:
            DATABASE_CLIENT: mysql
            DATABASE_HOST: mysql
            DATABASE_PORT: 3306
            DATABASE_NAME: plandb
            DATABASE_USERNAME: admin
            DATABASE_PASSWORD: admin
            DATABASE_SSL: 'false'
        volumes:
            - ./strapi:/srv/app
        ports:
            - '1337:1337'
        depends_on:
            - mysql

    frontend:
        build: ./frontend
        container_name: planning_frontend
        ports:
            - '8080:8080'
        volumes:
            - ./frontend:/app
            - /app/node_modules
        depends_on:
            - strapi